#!/usr/bin/env bash

# Generated by cron-setup.js
# Hope Theory Shadow Clone Jutsu — Daily Rhythm

set -e

# crypto_sage: morning_market_check
hermes -p crypto_sage cron create "0 9 * * *" \
  "Analyze BTC/ETH overnight. Identify 3 chart patterns. Log to #ShadowNetwork (shadow-kanban)."

# crypto_sage: weekly_sentiment
hermes -p crypto_sage cron create "0 18 * * 0" \
  "Generate weekly sentiment report. Fear/Greed, funding rates, social trends."

# crypto_sage: monthly_mining_audit
hermes -p crypto_sage cron create "0 10 1 * *" \
  "Calculate mining profitability. ROI per rig. Recommend continue/upgrade/exit."

# code_ninja: weekly_code_review
hermes -p code_ninja cron create "0 18 * * 5" \
  "Review all active client projects. Update skill library. Identify reusable patterns."

# code_ninja: monthly_skill_update
hermes -p code_ninja cron create "0 10 1 * *" \
  "Scan new tools/frameworks. Update skills/ folder. Test in playground."

# code_ninja: daily_git_status
hermes -p code_ninja cron create "0 20 * * *" \
  "Check git status of all active repos. Flag uncommitted work > 24h."

# marjahans_merchant: daily_inventory
hermes -p marjahans_merchant cron create "0 10 * * *" \
  "Check Shopify inventory. Flag SKUs < 5 units. Suggest reorder."

# marjahans_merchant: weekly_email_campaign
hermes -p marjahans_merchant cron create "0 9 * * 1" \
  "Draft weekly Klaviyo email. Product story, customer testimonial, CTA."

# marjahans_merchant: monthly_competitor_scan
hermes -p marjahans_merchant cron create "0 11 1 * *" \
  "Scan top 5 competitors. Pricing, new products, campaigns. Recommend actions."

# marjahans_merchant: daily_engagement
hermes -p marjahans_merchant cron create "0 14 * * *" \
  "Reply to all IG DMs and comments. Engage 10 accounts in our niche."

# snaptrap_stylist: daily_culture_scan
hermes -p snaptrap_stylist cron create "0 11 * * *" \
  "Scan TikTok, IG, Pinterest, X. Identify trending aesthetics, sounds, hashtags. Log 5 trends."

# snaptrap_stylist: weekly_community_check
hermes -p snaptrap_stylist cron create "0 18 * * 3" \
  "Review IG DMs, comments, mentions. Engage top 20 accounts. Flag UGC."

# snaptrap_stylist: pre_drop_teaser
hermes -p snaptrap_stylist cron create "0 20 * * *" \
  "If drop is 7-14 days out: post teaser content. If < 24h: countdown."

# build_master: weekly_pipeline_review
hermes -p build_master cron create "0 9 * * 1" \
  "Review all open proposals. Update CRM. Follow up on warm intros > 7 days old."

# build_master: monthly_proposal_followup
hermes -p build_master cron create "0 10 1 * *" \
  "Check status of all proposals sent > 30 days ago. Decide: pursue, archive, or warm up."

# build_master: daily_network_check
hermes -p build_master cron create "0 8 * * *" \
  "Check LinkedIn, email, WhatsApp for new contacts. Log to CRM. Identify warm intro paths."

# truth_seeker: daily_research_scan
hermes -p truth_seeker cron create "0 8 * * *" \
  "Scan crypto, history, philosophy, technology. Identify 3 macro patterns. Draft 1 thread."

# truth_seeker: weekly_newsletter
hermes -p truth_seeker cron create "0 9 * * 0" \
  "Draft weekly Substack. Connect 2-3 events to historical/philosophical pattern. 1500-2000 words."

# truth_seeker: monthly_audience_review
hermes -p truth_seeker cron create "0 10 1 * *" \
  "Analyze Substack, YouTube, X growth. Identify top-performing content. Recommend topics."

# truth_seeker: daily_posting
hermes -p truth_seeker cron create "0 12,18,21 * * *" \
  "Post 1 thread or tweet at peak time. Engage replies within 2 hours."

# naruto_main: morning_synthesis
hermes -p naruto_main cron create "30 9 * * *" \
  "Run shadow-orchestrator synthesis. Deliver State of the Empire."

# naruto_main: evening_memory
hermes -p naruto_main cron create "0 22 * * *" \
  "Run shadow-orchestrator memory. Tag insights, save to ShadowNetwork."

# naruto_main: weekly_review
hermes -p naruto_main cron create "0 20 * * 0" \
  "Run shadow-orchestrator weekly. Sunday digest."
